eureka:
  client:
    serviceUrl:
      defaultZone: https://mentorapp-serviceregistry.herokuapp.com/eureka/
ldap:
  user:
    dn:
      pattern: uid={0}
server:
  port: 8081
spring:
  application:
    name: mentorapp-user
  ldap:
    base: dc=example,dc=com
    password: password
    urls: ldap://ldap.forumsys.com:389/
    username: cn=read-only-admin,dc=example,dc=com
